### ISSUE TITLE
0.0.3 doesn't work with latest tornado (6.0.0)

### ISSUE THREAD

**Issue by jeroendecroos** [googlecolab/jupyter_http_over_ws#5]
'Tornado' released '6.0.0' on 01/03/2019, making 'jupyter_http_over_ws' raising an ImportError when invoking:

`jupyter serverextension enable --py jupyter_http_over_ws`

```
https://github.com/tornadoweb/tornado/issues/2383
 File "<site-packages\jupyter_http_over_ws\handlers.py", line 28, in <module>
    from tornado import stack_context
ImportError: cannot import name 'stack_context'
```

Using tornado==5.1 makes it work.

**Comment by craigcitro** [comment]
Thanks for the report! We'll work on tweaking setup.py accordingly.

Internal tracking: b/127337807

**Comment by colaboratory-team** [comment]
For now, we've restricted our setup.py to only install Tornado versions <6. You should be able to update your extension by running the following command:

`pip install --upgrade jupyter_http_over_ws`

Note that running the command will also downgrade your installed version of Tornado. Marking this as fixed, but please do reopen if you still encounter problems.
